force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/CardSet__c.field-meta.xml
<CustomField>
    <fullName>CardSet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card Set</label>
    <referenceTo>CardSet__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CardSet__c/CardSet__c.object-meta.xml
<CustomObject>
    <label>Card Set</label>
    <nameField>
        <label>Card Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CardSet__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Card Sets</relationshipLabel>
    <relationshipName>CardSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/cardMakerController.cls
public without sharing class cardMakerController {
    @AuraEnabled
    public static List<CardSet__c> getUserSets(){
        String usrId = UserInfo.getUserId();
        Student__c student = [SELECT Id FROM Student__c WHERE User__c = :usrId];
        String studentId = student.Id;
        List<CardSet__c> sets = [SELECT Id, Name FROM CardSet__c WHERE Student__c  = :studentId];
        return sets;
    }

    @AuraEnabled
    public static String createCardSet(String setName){
        String usrId = UserInfo.getUserId();
        Student__c student = [SELECT Id FROM Student__c WHERE User__c = :usrId];
        String studentId = student.Id;

        CardSet__c cardSet = new CardSet__c();
        cardSet.Name = setName;
        cardSet.Student__c = studentId;
        insert cardSet;
        return cardSet.Id;
    }

    @AuraEnabled
    public static List<Card__c> getSetCards(String setId){
        List<Card__c> cards = [SELECT Id, CardSet__c, Question__c, Answer__c FROM Card__c WHERE CardSet__c = :setId];
        return cards;
    }

    @AuraEnabled
    public static void  deleteCard(String cardId){
        delete [SELECT Id FROM Card__C WHERE Id = :cardId];
    }

    @AuraEnabled
    public static void deleteCardSet(String setId){
        List<Card__c> cards = [SELECT Id FROM Card__c WHERE CardSet__c = :setId];
        delete cards;
        delete [SELECT Id FROM CardSet__c WHERE Id = :setId];
    }
}