force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassSubject__c/ClassSubject__c.object-meta.xml
<CustomObject>
    <label>Class&apos; subject</label>
    <nameField>
        <label>Class&apos; Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class&apos; subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassSubject__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassSubject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School__c/School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachersSubject__c/TeachersSubject__c.object-meta.xml
<CustomObject>
    <label>Teacher&apos;s Subject</label>
    <nameField>
        <label>Teacher&apos;s Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teacher&apos;s Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeachersSubject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Teacher&apos;s Subjects</relationshipLabel>
    <relationshipName>TeachersSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachersSubject__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Teacher&apos;s Subjects</relationshipLabel>
    <relationshipName>TeachersSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/topicMakerController.cls
public without sharing class topicMakerController {
    @AuraEnabled
    public static List<Class__c> getTeacherClasses(){
        System.debug(LoggingLevel.INFO, 'TeachClass');
        String usrId = UserInfo.getUserId();     
        Teacher__c teaher = [SELECT Id, School__c FROM Teacher__c WHERE User__c = :usrId];
        String teacherId = teaher.Id;
        List<TeachersSubject__c> teaherSubject = [SELECT Id, Subject__c FROM TeachersSubject__c WHERE Teacher__c = :teacherId];
        Set<Id> subjectsId = new Set<Id>();
        for (TeachersSubject__c variable : teaherSubject) {
            subjectsId.add(variable.Subject__c);
        }
        List<ClassSubject__c> classSubject = [SELECT Id, Class__c FROM ClassSubject__c WHERE Subject__c IN :subjectsId];
        Set<Id> classesId = new Set<Id>();
        for (ClassSubject__c variable : classSubject) {
            classesId.add(variable.Class__c);
        }
        return [SELECT
            Id,
            Grade__c,
            School__c,
            Suffix__c,
            Name
        FROM
            Class__c
        WHERE
            Id IN :classesId
        ORDER BY Grade__c];
    }


}