force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassSubject__c/ClassSubject__c.object-meta.xml
<CustomObject>
    <label>Class&apos; subject</label>
    <nameField>
        <label>Class&apos; Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class&apos; subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassSubject__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassSubject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School__c/School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachersSubject__c/TeachersSubject__c.object-meta.xml
<CustomObject>
    <label>Teacher&apos;s Subject</label>
    <nameField>
        <label>Teacher&apos;s Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teacher&apos;s Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeachersSubject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Teacher&apos;s Subjects</relationshipLabel>
    <relationshipName>TeachersSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachersSubject__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Teacher&apos;s Subjects</relationshipLabel>
    <relationshipName>TeachersSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/classChooseController.cls
public without sharing class classChooseController {
    @AuraEnabled
    public static List<Class__c> getAvialibleClasses(){
        String usrId = UserInfo.getUserId();     
        Teacher__c teaher = [SELECT Id, School__c FROM Teacher__c WHERE User__c = :usrId];
        String schoolId = teaher.School__c;
        List<Class__c> classes = [SELECT Id, Grade__c, Suffix__c, School__c FROM Class__c WHERE School__c = :schoolId ORDER BY Grade__c];
        return classes;
    }

    @AuraEnabled
    public static List<Subject__c> getClassSubjects(String classId){
        List<ClassSubject__c> classSub = [SELECT Id, Subject__c FROM ClassSubject__c WHERE Class__c = :classId];
        Set<Id> subId = new Set<Id>();
        for (ClassSubject__c variable : classSub) {
            subId.add(variable.Subject__c);
        }
        List<Subject__c> sub = [SELECT Id, Name FROM Subject__c WHERE Id IN :subId];
        return sub;
    }

    @AuraEnabled
    public static List<Subject__c> getTeacherClassSubjects(String classId){
        String usrId = UserInfo.getUserId();     
        Teacher__c teaher = [SELECT Id, School__c FROM Teacher__c WHERE User__c = :usrId];
        String teacherId = teaher.Id;
        List<TeachersSubject__c> teachSub = [SELECT Id, Subject__c FROM TeachersSubject__c];
        Set<Id> subjects = new Set<Id>();
        for (TeachersSubject__c variable : teachSub) {
            subjects.add(variable.Subject__c);
        }
        List<ClassSubject__c> classSub = [SELECT Id, Class__c, Subject__c FROM ClassSubject__c WHERE (Class__c = :classId AND Subject__c IN :subjects)];
        subjects.clear();
        for (ClassSubject__c variable : classSub) {
            subjects.add(variable.Subject__c);
        }
        List<Subject__c> resultSub = [SELECT Id, Name FROM Subject__c WHERE Id IN :subjects];
        return resultSub;
    }
}