force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Key__c/Key__c.object-meta.xml
<CustomObject>
    <label>Key</label>
    <nameField>
        <label>Key Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Keys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Key__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Keys</relationshipLabel>
    <relationshipName>Keys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Key__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Keys</relationshipLabel>
    <relationshipName>Keys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Key__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Teacher</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/School__c/School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegisterController.cls
public without sharing class RegisterController {

    public static final String COMMUNITY_ACCOUNT = '0010900000GDgDbAAL';
    public static final String PROFILE_ID = '00e09000001EfzXAAS';

	public RegisterController () {}

	private final Long CURRENT_TIME = Datetime.now().getTime();
    public String key {get; set;}
	public String Firstname {get; set;}
	public String email {get; set;}
	public String password {get; set {password = value == null ? value : value.trim(); } }
	public String confirmPassword {get; set { confirmPassword = value == null ? value : value.trim(); } }
	public String Lastname {get; set { Lastname = value == null ? value : value.trim(); } }
	public String e;

	public String getE () {
		return e;
	}

	public PageReference registerUser() {

		try{

            Key__c keyObj = getKeyByValue(key);

            if (keyObj == null) {
                return null;
            }   

            String userType = keyObj.Type__c;

            // User u = new User();

            // u.username = email;
            // u.Email = email;
            // u.FirstName = Firstname;
            // u.LastName = Lastname;
            // u.CommunityNickname = generateCommunityNickname();
            // u.ProfileId = PROFILE_ID;
            // u.IsTeacher__c = userType == 'Teacher' ? true : false;

            Account acc = new Account(Name = generateCommunityNickname());

			insert acc;

            Contact cont = new Contact(FirstName = Firstname, LastName = Lastname, Email = email, AccountId = acc.Id);

			insert cont;

            User portalUser = new User(
				ProfileId = PROFILE_ID,
				Username = email,
				Alias = 'sfdc',
				Email = email,
				EmailEncodingKey='UTF-8',
				Firstname=Firstname,
				Lastname=Lastname,
				LanguageLocaleKey='en_US',
				LocaleSidKey='en_US',
				TimeZoneSidKey='GMT',
				ContactId = cont.Id,
                IsTeacher__c = userType == 'Teacher' ? true : false
				);

            insert portalUser;

			System.setPassword(portalUser.ID, password);

            // String userId = Site.createPortalUser(u, COMMUNITY_ACCOUNT, password);

            if (portalUser.IsTeacher__c = false) {
                createStudent(keyObj, portalUser, portalUser.ID);
            } else {
                createTeacher(keyObj, portalUser, portalUser.Id);
            }

            return Site.login(email, password, null);
		} catch (Exception ex) {
			e = ex.getMessage();
		}
		return null;
	}

    private Teacher__c createTeacher(Key__c keyObj, User u, String userId) {

        Teacher__c teacher = new Teacher__c();

        teacher.School__c = keyObj.School__c;
        teacher.User__c = userId;
        teacher.Name = u.FirstName + ' ' + u.LastName;

        insert teacher;

        keyObj.IsUsed__c = true;

        update keyObj;

        return teacher;
    }

    private Student__c createStudent (Key__c keyObj, User u, String userId) {
        Student__c student = new Student__c();

        student.Name = u.FirstName + ' ' + u.LastName;
        student.Class__c = keyObj.Class__c;
        student.School__c = keyObj.School__c;
        student.User__c = userId;

        insert student;

        keyObj.IsUsed__c = true;

        update keyObj;

        return student;
    }

    private Key__c getKeyByValue(String value) {
        return [SELECT Id, Value__c, Class__c, School__c, Type__c FROM Key__c WHERE Value__c =: value AND IsUsed__c = false LIMIT 1];
    }

	private String generateCommunityNickname() {
		return 'ExternalUser' + CURRENT_TIME;
	}
}