force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassSubject__c/ClassSubject__c.object-meta.xml
<CustomObject>
    <label>Class&apos; subject</label>
    <nameField>
        <label>Class&apos; Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class&apos; subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassSubject__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassSubject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/topicViewController.cls
public without sharing class topicViewController {
    @AuraEnabled
    public static List<Subject__c> getUserClasses(){
        String usrId = UserInfo.getUserId();
        Student__c student = [SELECT Id, Class__c FROM Student__c WHERE User__c = :usrId];
        String userClass = student.Class__c;
        List<ClassSubject__c> classSubjects = [SELECT id, Subject__c, Class__c FROM ClassSubject__c WHERE Class__c = :userClass];
        Set<Id> subjects = new Set<Id>();
        for (ClassSubject__c variable : classSubjects) {
            subjects.add(variable.Subject__c);
        }
        return [SELECT Id, Name FROM Subject__c WHERE Id IN :subjects];
    }

    @AuraEnabled
    public static List<Topic__c> getSubjectTopics(String subjectId){
        return [SELECT Id, Title__c FROM Topic__c WHERE Subject__c = :subjectId];
    }

    @AuraEnabled
    public static List<ContentDocument> getDocumentByTopic(String topicId){
        List<ContentDocumentLink> links = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :topicId];
        Set<Id> ids = new Set<Id>();
        for (ContentDocumentLink variable : links) {
            ids.add(variable.ContentDocumentId);
        }
        List<ContentDocument> documents = [SELECT Id, Title, FileType FROM ContentDocument WHERE Id IN : ids ORDER BY CreatedDate];
        return documents;
    }

    @AuraEnabled
    public static String getFileUrl(String documentId){
        ContentDistribution ds = [SELECT Id, DistributionPublicUrl FROM ContentDistribution WHERE ContentDocumentId = :documentId];
        return ds.DistributionPublicUrl;
    }
}