force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassSubject__c/ClassSubject__c.object-meta.xml
<CustomObject>
    <label>Class&apos; subject</label>
    <nameField>
        <label>Class&apos; Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class&apos; subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassSubject__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassSubject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Homework__c/Homework__c.object-meta.xml
<CustomObject>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Homework__c/fields/IsControlWork__c.field-meta.xml
<CustomField>
    <fullName>IsControlWork__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Control Work</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Homework__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Homeworks</relationshipLabel>
    <relationshipName>Homeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MyAssignmentsController.cls
public without sharing class MyAssignmentsController {
    
    @AuraEnabled(Cacheable=true)
    public static Class__c getClass(){
        try {
            
            String userId = UserInfo.getUserId();

            Student__c student = [SELECT Id, Name, Class__c FROM Student__c WHERE User__c =: userId LIMIT 1];
            Class__c stdClass = [SELECT Id, Name FROM Class__C WHERE Id =: student.Class__c];

            return stdClass;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(Cacheable=true)
    public static Map<String, List<Topic__c>> getSubjects(String classId){
            List<ClassSubject__c> classSubjects = [SELECT Id, Name, Subject__c FROM ClassSubject__c WHERE Class__c =: classId];

            Set<Id> subjectsId = new Set<Id>();
            for (ClassSubject__c classSubject : classSubjects) {
                subjectsId.add(classSubject.Subject__c);
            }

            List<Subject__c> subjects = [SELECT Id, Name, (SELECT Id, Name FROM Topics__r) FROM Subject__c WHERE Id IN: subjectsId];

            Set<Id> topicsId = new Set<Id>();

            for(Subject__c sub : subjects){
                for (Topic__c top : sub.Topics__r) {
                    topicsId.add(top.Id);
                }
            }

            List<Topic__c> topics = [SELECT Id, Name, Subject__r.Name, Title__c, (SELECT Id, Name, IsControlWork__c FROM Homeworks__r) FROM Topic__c WHERE Id IN: topicsId];
            Map<String, List<Topic__c>> resultMap = new Map<String, List<Topic__c>>();

            for (Topic__c top : topics) {

                if (!resultMap.containsKey(top.Subject__r.Name)) {
                    resultMap.put(top.Subject__r.Name, new List<Topic__c>());
                }

                resultMap.get(top.Subject__r.Name).add(top);
            }


            return resultMap;
       
    }
}