force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Homework__c/Homework__c.object-meta.xml
<CustomObject>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentsHomework__c/StudentsHomework__c.object-meta.xml
<CustomObject>
    <label>Student&apos;s Homework</label>
    <nameField>
        <label>Student&apos;s Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student&apos;s Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentsHomework__c/fields/Homework__c.field-meta.xml
<CustomField>
    <fullName>Homework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Homework</label>
    <referenceTo>Homework__c</referenceTo>
    <relationshipLabel>Student&apos;s Homeworks</relationshipLabel>
    <relationshipName>StudentHomeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentsHomework__c/fields/Mark__c.field-meta.xml
<CustomField>
    <fullName>Mark__c</fullName>
    <label>Mark</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StudentsHomework__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Student&apos;s Homeworks</relationshipLabel>
    <relationshipName>StudentHomeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test</label>
    <referenceTo>Test__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Var1__c.field-meta.xml
<CustomField>
    <fullName>Var1__c</fullName>
    <label>Var1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Var2__c.field-meta.xml
<CustomField>
    <fullName>Var2__c</fullName>
    <label>Var2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Var3__c.field-meta.xml
<CustomField>
    <fullName>Var3__c</fullName>
    <label>Var3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/fields/Homework__c.field-meta.xml
<CustomField>
    <fullName>Homework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Homework</label>
    <referenceTo>Homework__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testProcessingController.cls
public without sharing class testProcessingController {
    @AuraEnabled
    public static Test__c getTest(String testId){
        Test__c test = [SELECT
        Id,
        Name,
        (
            SELECT
                Id,
                Var1__c,
                Var2__c,
                Var3__c,
                Question__c
            FROM
                Tasks__r
        )
        FROM
        Test__c WHERE Id = :testId LIMIT 1];
        return test;
    }

    @AuraEnabled
    public static void createStudentsHomework(String title, Integer mark, String testId){
        StudentsHomework__c stHome = new StudentsHomework__c();
        stHome.Mark__c = mark;
        stHome.Name = title;
        String usrId = UserInfo.getUserId();
        Student__c student = [SELECT Id, Class__c FROM Student__c WHERE User__c = :usrId];
        stHome.Student__c = student.Id;
        Test__c test = [SELECT Id, Homework__c FROM Test__c WHERE Id = :testId];
        stHome.Homework__c = test.Homework__c;
        insert stHome;
    }
}