force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Homework__c/Homework__c.object-meta.xml
<CustomObject>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Homework__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Homeworks</relationshipLabel>
    <relationshipName>Homeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentsHomework__c/StudentsHomework__c.object-meta.xml
<CustomObject>
    <label>Student&apos;s Homework</label>
    <nameField>
        <label>Student&apos;s Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student&apos;s Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentsHomework__c/fields/Homework__c.field-meta.xml
<CustomField>
    <fullName>Homework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Homework</label>
    <referenceTo>Homework__c</referenceTo>
    <relationshipLabel>Student&apos;s Homeworks</relationshipLabel>
    <relationshipName>StudentHomeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentsHomework__c/fields/Mark__c.field-meta.xml
<CustomField>
    <fullName>Mark__c</fullName>
    <label>Mark</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StudentsHomework__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Student&apos;s Homeworks</relationshipLabel>
    <relationshipName>StudentHomeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ToEvaluateController.cls
public without sharing class ToEvaluateController {
    
    @AuraEnabled
    public static List<Object> getStudentsHomeworks(
        String classId,
        String topicId,
        String subjectId
    ){
        List<Homework__c> homeworks = [SELECT Id, Name FROM Homework__c WHERE Topic__c =: topicId];
        Set<Id> hIds = new Set<Id>();

        for (Homework__c homework : homeworks) {
            hIds.add(homework.Id);
        }

        List<StudentsHomework__c> stdHomeworks = [SELECT Id, Name,
                                                 (SELECT ContentDocumentId FROM ContentDocumentLinks)
                                                  FROM StudentsHomework__c 
                                                  WHERE Homework__c IN: hIds AND Student__r.Class__c =: classId AND Mark__c = null];

        return stdHomeworks;
    }

    @AuraEnabled
    public static void updateHomework(String recordId, Integer mark){
        StudentsHomework__c stdHomework = new StudentsHomework__c(
            Id = recordId, Mark__c = mark
        );

        update stdHomework;
    }

}