force-app/main/default/objects/CalendarEntry__c/CalendarEntry__c.object-meta.xml
<CustomObject>
    <label>Calendar Entry</label>
    <nameField>
        <label>Calendar Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarEntry__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>CalendarEntries</relationshipLabel>
    <relationshipName>CalendarEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalendarEntry__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>CalendarEntries</relationshipLabel>
    <relationshipName>CalendarEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassSubject__c/ClassSubject__c.object-meta.xml
<CustomObject>
    <label>Class&apos; subject</label>
    <nameField>
        <label>Class&apos; Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class&apos; subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassSubject__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassSubject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Class&apos; subjects</relationshipLabel>
    <relationshipName>ClassSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Homework__c/Homework__c.object-meta.xml
<CustomObject>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Homework__c/fields/IsControlWork__c.field-meta.xml
<CustomField>
    <fullName>IsControlWork__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Control Work</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Homework__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Homeworks</relationshipLabel>
    <relationshipName>Homeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Homework__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>File</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/School__c/School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachersSubject__c/TeachersSubject__c.object-meta.xml
<CustomObject>
    <label>Teacher&apos;s Subject</label>
    <nameField>
        <label>Teacher&apos;s Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teacher&apos;s Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeachersSubject__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Teacher&apos;s Subjects</relationshipLabel>
    <relationshipName>TeachersSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachersSubject__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Teacher&apos;s Subjects</relationshipLabel>
    <relationshipName>TeachersSubjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/fields/Homework__c.field-meta.xml
<CustomField>
    <fullName>Homework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Homework</label>
    <referenceTo>Homework__c</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testMakerController.cls
public without sharing class testMakerController {
    @AuraEnabled
    public static Class__c[] getTeacherClasses(){
        String usrId = UserInfo.getUserId();     
        Teacher__c teaher = [SELECT Id FROM Teacher__c WHERE User__c = :usrId];
        TeachersSubject__c[] teaherSubject = [SELECT Id, Subject__c FROM TeachersSubject__c WHERE Teacher__c = :teaher.Id];
        Set<Id> subjectsId = new Set<Id>();
        for (TeachersSubject__c variable : teaherSubject) {
            subjectsId.add(variable.Subject__c);
        }
        ClassSubject__c[] classSubject = [SELECT Id, Class__c FROM ClassSubject__c WHERE Subject__c IN :subjectsId];
        Set<Id> classesId = new Set<Id>();
        for (ClassSubject__c variable : classSubject) {
            classesId.add(variable.Class__c);
        }
        return [SELECT
            Id,
            Grade__c,
            School__c,
            Suffix__c,
            Name
        FROM
            Class__c
        WHERE
            Id IN :classesId
        ORDER BY Grade__c];
    }

    @AuraEnabled
    public static List<Subject__c> getClassSubjects(String classId){
        List<ClassSubject__c> classSub = [SELECT Id, Subject__c FROM ClassSubject__c WHERE Class__c = :classId];
        Set<Id> subId = new Set<Id>();
        for (ClassSubject__c variable : classSub) {
            subId.add(variable.Subject__c);
        }
        List<Subject__c> sub = [SELECT Id, Name FROM Subject__c WHERE Id IN :subId];
        return sub;
    }

    @AuraEnabled
    public static List<Topic__c> getSubjectTopics(String subjectId){
        List<Topic__c> topics = [SELECT Id, Subject__c, Title__c FROM Topic__c WHERE Subject__c = :subjectId];
        return topics;
    }

    @AuraEnabled
    public static String createCalendarEntry(Datetime startDate, Datetime endDate, String Name, String classId, String message){
        String usrId = UserInfo.getUserId();     
        Teacher__c teaher = [SELECT Id FROM Teacher__c WHERE User__c = :usrId];
        CalendarEntry__c entry = new CalendarEntry__c();
        entry.StartDate__c = startDate;
        entry.EndDate__c = endDate;
        entry.Name = Name;
        entry.Message__c = Name;
        entry.Teacher__c = teaher.Id;
        entry.Class__c = classId;
        insert entry;
        return entry.Id;
    }

    @AuraEnabled
    public static String createHomework(String testTitle, String topicId, Datetime startDate, Datetime endDate, String classId){
        Homework__c work = new Homework__c();
        work.Type__c = 'Test';
        work.Title__c = testTitle;
        work.Topic__c = topicId;
        work.IsControlWork__c = true;
        work.StartDate__c = startDate;
        work.EndDate__c = endDate;
        insert work;
        createCalendarEntry(startDate, endDate, testTitle, classId, testTitle);
        return work.Id;
    }

    @AuraEnabled
    public static String createTest(String title, String homeworkId){
        Test__c test = new Test__c();
        test.Name = title;
        test.Homework__c = homeworkId;
        insert test;
        return test.Id;
    }
}