force-app/main/default/objects/Homework__c/Homework__c.object-meta.xml
<CustomObject>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentsHomework__c/StudentsHomework__c.object-meta.xml
<CustomObject>
    <label>Student&apos;s Homework</label>
    <nameField>
        <label>Student&apos;s Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student&apos;s Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentsHomework__c/fields/Homework__c.field-meta.xml
<CustomField>
    <fullName>Homework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Homework</label>
    <referenceTo>Homework__c</referenceTo>
    <relationshipLabel>Student&apos;s Homeworks</relationshipLabel>
    <relationshipName>StudentHomeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentsHomework__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Student&apos;s Homeworks</relationshipLabel>
    <relationshipName>StudentHomeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/homeworkProcessingController.cls
public without sharing class homeworkProcessingController {
    @AuraEnabled
    public static String getFileUrl(String documentId){
        ContentDistribution ds = [SELECT Id, DistributionPublicUrl FROM ContentDistribution WHERE ContentDocumentId = :documentId LIMIT 1];
        return ds.DistributionPublicUrl;
    }

    @AuraEnabled
    public static void createStudentsHomework(String documentId, String assignmentDocumentId){
        
        List<ContentDocumentLink> links = [SELECT Id, LinkedEntityId, ContentDocument.Title FROM ContentDocumentLink WHERE ContentDocumentId =: assignmentDocumentId];

        ContentDocumentLink link;

        for (ContentDocumentLink searchLink : links) {
            if (String.valueOf(searchLink.LinkedEntityId).startsWith('a06')) {
                link = searchLink;
                break;
            }
        }

        Student__c std = [SELECT Id FROM Student__c WHERE User__c =: UserInfo.getUserId()];

        Homework__c homework = [SELECT Id, Name FROM Homework__c WHERE Id =: link.LinkedEntityId];

        StudentsHomework__c stdHomework = new StudentsHomework__c();
        stdHomework.Name = link.ContentDocument.Title;
        stdHomework.Homework__c = homework.Id;
        stdHomework.Student__c = std.Id;

        insert stdHomework;

        ContentDocumentLink newLink = new ContentDocumentLink();
        newLink.ContentDocumentId = documentId;
        newLink.LinkedEntityId = stdHomework.Id;

        insert newLink;
    }
}