force-app/main/default/objects/Homework__c/Homework__c.object-meta.xml
<CustomObject>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Homework__c/fields/IsControlWork__c.field-meta.xml
<CustomField>
    <fullName>IsControlWork__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Control Work</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Homework__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Homeworks</relationshipLabel>
    <relationshipName>Homeworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Homework__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>File</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HomeworkMakerController.cls
public without sharing class HomeworkMakerController {
    @AuraEnabled
    public static void createLink(String recordId, String documentId){
        
        ContentDocumentLink link = new ContentDocumentLink();

        link.ContentDocumentId = documentId;
        link.LinkedEntityId = recordId;

        insert link;

    }

    @AuraEnabled
    public static String createHomework(String testTitle, String topicId, Datetime startDate, Datetime endDate, String classId){
        Homework__c work = new Homework__c();
        work.Type__c = 'Homework';
        work.Title__c = testTitle;
        work.Topic__c = topicId;
        work.IsControlWork__c = false;
        work.StartDate__c = startDate;
        work.EndDate__c = endDate;
        insert work;
        testMakerController.createCalendarEntry(startDate, endDate, testTitle, classId, testTitle);
        return work.Id;
    }
}